name: CI-CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4

      - name: Autenticacao no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # Dica: prefira Access Token em vez da senha real!

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bernardorocha/aula-primeira-pipeline:v${{ github.run_number }}